version: "3.5"
services:
  receive:
    ipc: host
    shm_size: 20000000
    network_mode: "host"
    privileged: true
    entrypoint: /scripts/receive.sh
    build: .
    volumes:
      - /dev:/dev
      - /tmp:/tmp    
  send:
    ipc: host
    network_mode: "host"
    shm_size: 20000000
    privileged: true
    entrypoint: /scripts/send.sh
    build: . 
    volumes:
      - /dev:/dev
      - /tmp:/tmp
